kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    createdForProviderType: vsphere
    createdForResourceType: providers
stringData:
  insecureSkipVerify: "true"
  password: {{ .Values.esxi.password }}
  url: https://ns3181354.ip-51-210-221.eu/sdk
  user: {{ .Values.esxi.user }}
type: Opaque
